### ISSUE TITLE
LCS0

### ISSUE THREAD

**Issue by madhur4127** [bnslakki/Spoj#1]
I know this isn't an issue but please upload solution for [LCS0](http://www.spoj.com/problems/LCS0/), it has baffled everyone (even reds). Maybe there's much to learn from fastest solution.

**Comment by bnslakki** [comment]
Sorry to say but i am currently working on this algorithm as a side
project, so i can't upload solution at this moment.
Btw, "Allison and Dix (1986)" is the key of solution. First try to learn
this algo and bitmasking.
For fastest solution you need to further optimize your code(given by
Allison & Dix (1986)).
Good Luck.
*Happy Coding.*
